### PR TITLE
attempt to reduce bundle size

### PR DESCRIPTION
**Pull request by saihaj**

### CODE REVIEW

**Comment by B2o5T** [comment]
@saihaj would you still want work on this?

**Comment by saihaj** [comment]
> @saihaj would you still want work on this?

We could take this much I guess and merge it. Just removes one dependency. Thoughts? Also aren't we planning to redo docs with radix and stitches which means we will get rid of chakra, emotion?

**Comment by B2o5T** [comment]
@saihaj
> We could take this much I guess and merge it. Just removes one dependency. Thoughts?

yeah, we should

> Also aren't we planning to redo docs with radix and stitches which means we will get rid of chakra, emotion?

I agree with this, need to confirm by someone else

**Comment by Urigo** [comment]
@B2o5T if you agree with this, it's your call!

**Comment by B2o5T** [comment]
@Urigo I'm agree, let's choose when I do it, next sprint or this sprint

**Pull request closed without merging**
